#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\App_Code\Content.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\App_Code\Content.cshtml"
    using Snittlistan.Web.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class Content
    {

public static System.Web.WebPages.HelperResult Script(ScriptType type)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\App_Code\Content.cshtml"
 
    string src;
    switch (type)
    {
        case ScriptType.JQuery:
            src = "https://code.jquery.com/jquery.min.js";
            break;
        case ScriptType.JQueryValidate:
            src = "https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js";
            break;
        case ScriptType.JQueryValidateLocalized:
            src = "https://ajax.aspnetcdn.com/ajax/jQuery.Validate/1.6/localization/messages_se.js";
            break;
        case ScriptType.JQueryValidateUnobtrusive:
            src = "https://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.validate.unobtrusive.min.js";
            break;
        case ScriptType.JQueryUI:
            src = "https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/jquery-ui.min.js";
            break;
        case ScriptType.JQueryUII18N:
            src = "https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/i18n/jquery-ui-i18n.min.js";
            break;
        case ScriptType.Modernizr:
            src = "https://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.0.6-development-only.js";
            break;

        default:
            throw new ArgumentOutOfRangeException(nameof(type), type, null);
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <script src=\"");



#line 35 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, src);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" type=\"text/javascript\"></script>\r\n");



#line 36 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Favicon(UrlHelper url)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 39 "..\..\App_Code\Content.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");



#line 40 "..\..\App_Code\Content.cshtml"
             WebViewPage.WriteTo(@__razor_helper_writer, url.Content("~/favicon.ico"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 41 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Css(string scriptName, UrlHelper url)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 44 "..\..\App_Code\Content.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <link href=\"");



#line 45 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, url.Content("~/Content/css/" + scriptName));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" rel=\"stylesheet\" type=\"text/css\" />\r\n");



#line 46 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Css(CssType type)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 49 "..\..\App_Code\Content.cshtml"
 
    string src;
    switch (type)
    {
        case CssType.Blitzer:
            src = "https://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.10/themes/blitzer/jquery-ui.css";
            break;

        default:
            throw new ArgumentOutOfRangeException(nameof(type), type, null);
    }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <link href=\"");



#line 61 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, src);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" rel=\"Stylesheet\" type=\"text/css\" />\r\n");



#line 62 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult ControllerMenuLink(
    System.Web.Mvc.HtmlHelper helper,
    string text,
    string icon,
    string controller,
    string actionLink)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 71 "..\..\App_Code\Content.cshtml"
 
    var routeData = helper.ViewContext.RouteData.Values;
    var currentController = routeData["controller"];

    var liClass = string.Empty;
    if (string.Equals(controller, currentController as string, StringComparison.OrdinalIgnoreCase))
    {
        liClass = "active";
    }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"");



#line 81 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, liClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <a href=\"");



#line 82 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, actionLink);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><i class=\"");



#line 82 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, icon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>");



#line 82 "..\..\App_Code\Content.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n    </li>\r\n");



#line 84 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TeamLabel(
    string teamLevel,
    string team
)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 90 "..\..\App_Code\Content.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <span class=\"label ");



#line 91 "..\..\App_Code\Content.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("{0}{1}", "label-team-", teamLevel.ToLower()));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 91 "..\..\App_Code\Content.cshtml"
                                          WebViewPage.WriteTo(@__razor_helper_writer, team);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 92 "..\..\App_Code\Content.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
