#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/User/SetPassword.cshtml")]
    public partial class _Areas_V2_Views_User_SetPassword_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<SetPasswordViewModel>
    {
        public _Areas_V2_Views_User_SetPassword_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
  
    ViewBag.Title = "Ange lösenord";


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"span6\">\r\n        <h3>");


            
            #line 7 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        <p>Du måste ange ett lösenord.</p>\r\n");


            
            #line 9 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
         using (Html.BeginForm("SetPassword", "User", FormMethod.Post, new { @class = "form-horizontal"}))
        {
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
       Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary", new { message = "Det gick inte att ange lösenord."}));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
                                                                                                                                         
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
       Write(Html.Hidden("activationKey", Model.ActivationKey));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
                                                              

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""control-group"">
                <label class=""control-label"" for=""password"">Lösenord:</label>
                <div class=""controls"">
                    <input type=""password"" name=""password"" placeholder=""Skriv lösenord"" autofocus=""autofocus"" required=""required"" />
                </div>
            </div>
");



WriteLiteral(@"            <div class=""control-group"">
                <label class=""control-label"" for=""confirmPassword"">Upprepa lösenord:</label>
                <div class=""controls"">
                    <input type=""password"" name=""confirmPassword"" placeholder=""Skriv lösenordet igen"" required=""required"" />
                </div>
            </div>
");



WriteLiteral("            <div class=\"control-group\">\r\n                <div class=\"controls\">\r\n" +
"                    <button class=\"btn btn-primary\" type=\"submit\">Spara</button>" +
"\r\n                </div>\r\n            </div>\r\n");


            
            #line 30 "..\..\Areas\V2\Views\User\SetPassword.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
