version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: RavenDB.Client
    versions:
    - ">= 4.a, < 5"
  - dependency-name: RavenDB.Client
    versions:
    - ">= 5.a, < 6"
  - dependency-name: RavenDB.Embedded
    versions:
    - ">= 4.a, < 6"
