image:
  Visual Studio 2017
before_build:
  - nuget restore
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - Snittlistan.Test\bin\Release\bits
configuration: Release
