#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Hacker/Index.cshtml")]
    public partial class _Views_Hacker_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Hacker_Index_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Hacker\Index.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>FUCK OFF!!!!!</title>\r\n    <style typ" +
"e=\"text/css\">\r\n#fuckoff {\r\n    margin: 0 auto;\r\n    width: 540px;\r\n    height: 5" +
"12px;\r\n    background-image: url(");


            
            #line 13 "..\..\Views\Hacker\Index.cshtml"
                     Write(Url.Content("~/Content/css/images/fuckoff.jpg"));

            
            #line default
            #line hidden
WriteLiteral(");\r\n}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div id=\"fuckoff\"></div>\r\n</body>\r\n</ht" +
"ml>\r\n");


        }
    }
}
#pragma warning restore 1591
