#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/ActivityEdit/_ActivityEditor.cshtml")]
    public partial class _Areas_V2_Views_ActivityEdit__ActivityEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.ActivityEditController.ActivityEditViewModel>
    {
        public _Areas_V2_Views_ActivityEdit__ActivityEditor_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<div class=""control-group"">
    <label class=""control-label"" for=""season"">Säsong:</label>
    <div class=""controls"">
        <input type=""text""
               id=""season""
               name=""season""
               placeholder=""Säsong""
               title=""Ange säsong""
               pattern=""\d*""
               required=""required""
               value=""");


            
            #line 13 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
                 Write(Model.Season);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <span class=\"help-block\">\r\n            Ange säsongen för aktivitete" +
"n. Skriv första delen av säsongen, t.ex. <strong>");


            
            #line 15 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
                                                                                    Write(Model.Season);

            
            #line default
            #line hidden
WriteLiteral("</strong>&minus;");


            
            #line 15 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
                                                                                                                  Write(Model.Season + 1);

            
            #line default
            #line hidden
WriteLiteral(".\r\n            Vanligtvis är det redan rätt ifyllt.\r\n        </span>\r\n    </div>\r" +
"\n</div>\r\n<div class=\"control-group\">\r\n    ");


            
            #line 21 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
Write(Html.LabelFor(x => x.Title, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        ");


            
            #line 23 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
   Write(Html.TextBoxFor(x => x.Title, new { required = "required", maxlength = "80", autofocus = "autofocus" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    ");


            
            #line 27 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
Write(Html.LabelFor(x => x.Date, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        ");


            
            #line 29 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
   Write(Html.TextBoxFor(
            x => x.Date,
            new
            {
                @class = "date-picker",
                @readonly = "readonly",
                required = "required",
                placeholder = "Välj datum",
                data_datepicker = "",
                data_timepicker = "true"
            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    ");


            
            #line 43 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
Write(Html.LabelFor(x => x.MessageDisplay, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        <div data-quill>\r\n            ");


            
            #line 46 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
       Write(Model.MessageDisplay);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        ");


            
            #line 48 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
   Write(Html.HiddenFor(x => x.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 49 "..\..\Areas\V2\Views\ActivityEdit\_ActivityEditor.cshtml"
   Write(Html.HiddenFor(x => x.MessageHtml));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
