#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/ActivityEdit/Create.cshtml")]
    public partial class _Areas_V2_Views_ActivityEdit_Create_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.ActivityEditController.ActivityEditViewModel>
    {
        public _Areas_V2_Views_ActivityEdit_Create_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n");


            
            #line 5 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
         using (
            Html.BeginForm(
                "Create",
                "ActivityEdit",
                FormMethod.Post,
                new
                {
                    @class = "form-horizontal quill-form",
                    data_quill_data = new QuillData(
                        Html.NameFor(x => x.MessageHtml).ToString(),
                        Html.NameFor(x => x.Message).ToString(),
                        "Beskriv aktiviteten...").ToJson()
                }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <fieldset>\r\n                <legend>Skapa ny aktivitet</legend>\r\n    " +
"        </fieldset>\r\n");


            
            #line 22 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
       Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary"));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
                                                                                    
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
       Write(Html.Partial("_ActivityEditor", Model));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
                                                   

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"form-actions\">\r\n                <button class=\"btn btn-pr" +
"imary btn-large\" type=\"submit\">Spara</button>\r\n                ");


            
            #line 26 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
           Write(Html.ActionLink("Avbryt", "Index", "ActivityIndex", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 28 "..\..\Areas\V2\Views\ActivityEdit\Create.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
