#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/ActivityEdit/Delete.cshtml")]
    public partial class _Areas_V2_Views_ActivityEdit_Delete_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<ActivityViewModel>
    {
        public _Areas_V2_Views_ActivityEdit_Delete_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\V2\Views\ActivityEdit\Delete.cshtml"
Write(Html.DisplayForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n");


            
            #line 7 "..\..\Areas\V2\Views\ActivityEdit\Delete.cshtml"
         using (Html.BeginForm("Delete", "ActivityEdit", FormMethod.Post))
        {

            
            #line default
            #line hidden
WriteLiteral("            <fieldset>\r\n                <legend>Är du säker på att du vill ta bor" +
"t den här aktiviteten?</legend>\r\n            </fieldset>\r\n");



WriteLiteral("            <div class=\"form-actions\">\r\n                <button class=\"btn btn-da" +
"nger btn-large\" type=\"submit\">Ta bort</button>\r\n                ");


            
            #line 14 "..\..\Areas\V2\Views\ActivityEdit\Delete.cshtml"
           Write(Html.ActionLink("Avbryt", "Index", "ActivityIndex", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 16 "..\..\Areas\V2\Views\ActivityEdit\Delete.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
