#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Absence/_AbsenceEditor.cshtml")]
    public partial class _Areas_V2_Views_Absence__AbsenceEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.AbsenceController.CreateAbsenceViewModel>
    {
        public _Areas_V2_Views_Absence__AbsenceEditor_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"control-group\">\r\n    <label class=\"control-label\" for=\"player\">Spel" +
"are:</label>\r\n    <div class=\"controls\">\r\n        ");


            
            #line 6 "..\..\Areas\V2\Views\Absence\_AbsenceEditor.cshtml"
   Write(Html.DropDownList("Player", null, new { required = "required", id = "player" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    ");


            
            #line 10 "..\..\Areas\V2\Views\Absence\_AbsenceEditor.cshtml"
Write(Html.LabelFor(x => x.DateRange, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        ");


            
            #line 12 "..\..\Areas\V2\Views\Absence\_AbsenceEditor.cshtml"
   Write(Html.TextBoxFor(
            x => x.DateRange,
            new
            {
                @class = "date-picker",
                @readonly = "readonly",
                required = "required",
                placeholder = "Välj datum",
                data_datepicker = "",
                data_range = "true",
                data_multiple_dates_separator =" - "
            }));

            
            #line default
            #line hidden
WriteLiteral(@"
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""comment"">Kommentar:</label>
    <div class=""controls"">
        <input type=""text""
               name=""comment""
               id=""comment""
               maxlength=""160""
               value=""");


            
            #line 33 "..\..\Areas\V2\Views\Absence\_AbsenceEditor.cshtml"
                 Write(Model.Comment);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
