#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Absence/AbsenceTable.cshtml")]
    public partial class _Areas_V2_Views_Absence_AbsenceTable_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Indexes.AbsenceIndex.Result[]>
    {
        public _Areas_V2_Views_Absence_AbsenceTable_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
  
    Layout = null;
    var hideControls = ViewBag.HideControls;


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <table class=\"table table-" +
"condensed table-striped\">\r\n            <tr>\r\n                <th>Namn</th>\r\n    " +
"            <th></th>\r\n");


            
            #line 13 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                 if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th></th>\r\n");



WriteLiteral("                    <th></th>\r\n");


            
            #line 17 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");


            
            #line 19 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
             foreach (var absence in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");


            
            #line 22 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                      
                        var rowspan = string.IsNullOrWhiteSpace(absence.Comment) ? 1 : 2;
                    

            
            #line default
            #line hidden
WriteLiteral("                    <td class=\"center\" rowspan=\"");


            
            #line 25 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                           Write(rowspan);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 25 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                                     Write(absence.PlayerName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>\r\n                        ");


            
            #line 27 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                   Write(Html.FormatDateSpan(absence.From, absence.To));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n\r\n");


            
            #line 30 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                     if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td class=\"center\" rowspan=\"");


            
            #line 32 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                               Write(rowspan);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <a href=\"");


            
            #line 33 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                Write(Url.Action("Edit", new { id = absence.Id.Substring(absence.Id.LastIndexOf('-') + 1) }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <i class=\"sprite-glyphicons_151_edit\"></i>\r\n " +
"                           </a>\r\n                        </td>\r\n");



WriteLiteral("                        <td class=\"center\" rowspan=\"");


            
            #line 37 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                               Write(rowspan);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <a href=\"");


            
            #line 38 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                                Write(Url.Action("Delete", new { id = absence.Id.Substring(absence.Id.LastIndexOf('-') + 1) }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <i class=\"sprite-glyphicons_016_bin\"></i>\r\n  " +
"                          </a>\r\n                        </td>\r\n");


            
            #line 42 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");


            
            #line 44 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                if (string.IsNullOrWhiteSpace(absence.Comment) == false)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");


            
            #line 47 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                       Write(absence.Comment);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");


            
            #line 49 "..\..\Areas\V2\Views\Absence\AbsenceTable.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
