#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Absence/Delete.cshtml")]
    public partial class _Areas_V2_Views_Absence_Delete_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<AbsenceViewModel>
    {
        public _Areas_V2_Views_Absence_Delete_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
  
    ViewBag.Title = "Ta bort";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h4>Ta bort</h4>\r\n<p>Är du säker på att du vill ta bort denna registrerade från" +
"varo?</p>\r\n");


            
            #line 9 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
 using (Html.BeginForm("Delete", "Absence", FormMethod.Post))
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>");


            
            #line 11 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
   Write(Model.PlayerName);

            
            #line default
            #line hidden
WriteLiteral(" <em>(");


            
            #line 11 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
                          Write(Html.FormatDateSpan(Model.From, Model.To));

            
            #line default
            #line hidden
WriteLiteral(")</em></h3>\r\n");



WriteLiteral("    <button class=\"btn btn-danger btn-large\" type=\"submit\">Ta bort</button>\r\n");


            
            #line 13 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
Write(Html.ActionLink("Avbryt", "Index", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\V2\Views\Absence\Delete.cshtml"
                                                                               
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
