#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Absence/Index.cshtml")]
    public partial class _Areas_V2_Views_Absence_Index_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Indexes.AbsenceIndex.Result[]>
    {
        public _Areas_V2_Views_Absence_Index_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span8\">\r\n        <h4 class=\"pull-left\">Anmäl" +
"d frånvaro</h4>\r\n");


            
            #line 6 "..\..\Areas\V2\Views\Absence\Index.cshtml"
         if (User.IsInRole2(WebsiteRoles.Uk.UkTasks))
        {

            
            #line default
            #line hidden
WriteLiteral("            <a class=\"pull-right\" href=\"");


            
            #line 8 "..\..\Areas\V2\Views\Absence\Index.cshtml"
                                   Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <i class=\"sprite-glyphicons_006_user_add\"></i>\r\n             " +
"   Registrera frånvaro\r\n            </a>\r\n");


            
            #line 12 "..\..\Areas\V2\Views\Absence\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"clearfix\"></div>\r\n    </div>\r\n</div>\r\n");


            
            #line 16 "..\..\Areas\V2\Views\Absence\Index.cshtml"
Write(Html.Action("AbsenceTable"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
