#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/AdminRosterAccept/AcceptPlayer.cshtml")]
    public partial class _Areas_V2_Views_AdminRosterAccept_AcceptPlayer_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.AdminRosterAcceptController.ViewModel>
    {
        public _Areas_V2_Views_AdminRosterAccept_AcceptPlayer_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
  
    ViewBag.Title = "Välj spelare";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <div class=\"well well-smal" +
"l\">\r\n            ");


            
            #line 9 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
       Write(Html.DisplayFor(x => x.Header));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"span12\">" +
"\r\n");


            
            #line 15 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
         using (Html.BeginForm(
            "AcceptPlayer",
            "AdminRosterAccept",
            FormMethod.Post,
            new
            {
                @class = "form-horizontal"
            }))
        {
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
       Write(Html.HiddenFor(x => x.Model.RosterId));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
                                                  
            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
       Write(Html.HiddenFor(x => x.Model.Season));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
                                                
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
       Write(Html.HiddenFor(x => x.Model.Turn));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
                                              

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"control-group\">\r\n                ");


            
            #line 28 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
           Write(Html.LabelFor(x => x.Model.PlayerId, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div class=\"controls\">\r\n                    ");


            
            #line 30 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
               Write(Html.DropDownListFor(
                        x => x.Model.PlayerId,
                        (SelectListItem[])ViewBag.PlayerId,
                        new
                        {
                            required = "required",
                            id = "playerId"
                        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span class=\"help-block\">\r\n                        Välj spe" +
"lare som deltar.\r\n                    </span>\r\n                </div>\r\n         " +
"   </div>\r\n");



WriteLiteral("            <div class=\"control-group\">\r\n                <div class=\"controls\">\r\n" +
"                    <button class=\"btn btn-primary btn-large\" type=\"submit\">Spar" +
"a</button>\r\n                    <a class=\"btn btn-large\"\r\n                      " +
" href=\"");


            
            #line 47 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
                        Write(Url.Action(
                                 "View",
                                 "Roster",
                                 new
                                 {
                                     Model.Model.Season,
                                     Model.Model.Turn
                                 }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        Avbryt\r\n                    </a>\r\n                </d" +
"iv>\r\n            </div>\r\n");


            
            #line 59 "..\..\Areas\V2\Views\AdminRosterAccept\AcceptPlayer.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
