#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Authentication/EmailSent.cshtml")]
    public partial class _Areas_V2_Views_Authentication_EmailSent_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_Authentication_EmailSent_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V2\Views\Authentication\EmailSent.cshtml"
  
    ViewBag.Title = "Logga in";


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"span6\">\r\n        <h3>");


            
            #line 6 "..\..\Areas\V2\Views\Authentication\EmailSent.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</h3>
        <p>Du ska nu få ett e-postbrev till den angivna adressen. Där finns en länk du ska använda för att logga in.
            Om du inte fått brevet, ta en titt i skräppost för säkerhetsskull.</p>
        <p>Behöver du göra om inloggningen så börja igen ");


            
            #line 9 "..\..\Areas\V2\Views\Authentication\EmailSent.cshtml"
                                                    Write(Html.ActionLink("här", "LogOn"));

            
            #line default
            #line hidden
WriteLiteral(".</p>\r\n        <p>\r\n            Observera att du enbart har ett dygn på dig att a" +
"nvända länken i e-postbrevet. Efter det upphör den att gälla.\r\n        </p>\r\n   " +
" </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
