#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Authentication/LogOnPassword.cshtml")]
    public partial class _Areas_V2_Views_Authentication_LogOnPassword_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.AuthenticationController.PasswordViewModel>
    {
        public _Areas_V2_Views_Authentication_LogOnPassword_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\Authentication\LogOnPassword.cshtml"
  
    ViewBag.Title = "Logga in";


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"span6\">\r\n        <h3>");


            
            #line 7 "..\..\Areas\V2\Views\Authentication\LogOnPassword.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        <p>Ange nu ditt lösenord.</p>\r\n");


            
            #line 9 "..\..\Areas\V2\Views\Authentication\LogOnPassword.cshtml"
         using (Html.BeginForm("LogOnPassword", "Authentication", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            Html.RenderPartial("_PasswordEditor");
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
