#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Authentication/LogOn.cshtml")]
    public partial class _Areas_V2_Views_Authentication_LogOn_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.AuthenticationController.EmailViewModel>
    {
        public _Areas_V2_Views_Authentication_LogOn_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
  
    ViewBag.Title = "Logga in";


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"span6\">\r\n        <h3>");


            
            #line 7 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");


            
            #line 8 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
         if (ViewBag.PlayerId != null)
        {
            
            
            #line default
            #line hidden

            
            #line 11 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                                                                                                  
            using (Html.BeginForm("LogOn", "Authentication", FormMethod.Post, new
            {
                @class = "form-horizontal"
            }))
            {
                
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
           Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary", new
                {
                    message = "Det gick inte att logga in."
                }));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                  

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"control-group\">\r\n                    <label class=\"co" +
"ntrol-label\" for=\"playerId\">Spelare:</label>\r\n                    <div class=\"co" +
"ntrols\">\r\n                        ");


            
            #line 24 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                   Write(Html.DropDownList("PlayerId", null, new
                        {
                            required = "required",
                            id = "playerId"
                        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span class=\"help-block\">\r\n                            " +
"E-postadressen används för flera spelare. Välj den du vill logga in som.\r\n      " +
"                  </span>\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <div class=\"control-group\">\r\n                    <div class=\"cont" +
"rols\">\r\n                        <button class=\"btn btn-primary btn-large\" type=\"" +
"submit\">Logga in</button>\r\n                        <a class=\"btn btn-large\" href" +
"=\"");


            
            #line 37 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                                                  Write(Url.Action("Index", "Roster"));

            
            #line default
            #line hidden
WriteLiteral("\">Avbryt</a>\r\n                    </div>\r\n                </div>\r\n");


            
            #line 40 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
            }
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>Ange först din e-postadress.</p>\r\n");


            
            #line 45 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
            using (Html.BeginForm("LogOn", "Authentication", FormMethod.Post, new
            {
                @class = "form-horizontal"
            }))
            {
                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
           Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary", new
                {
                    message = "Det gick inte att logga in."
                }));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                  

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"control-group\">\r\n                    ");


            
            #line 55 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
               Write(Html.LabelFor(x => x.Email, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"controls\">\r\n                        ");


            
            #line 57 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                   Write(Html.TextBoxFor(
                            x => x.Email,
                            new
                            {
                                type = "email",
                                autofocus = "autofocus",
                                required = "required"
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <div class=\"control-group\">\r\n                    <div class=\"cont" +
"rols\">\r\n                        <button class=\"btn btn-primary btn-large\" type=\"" +
"submit\">Logga in</button>\r\n                        <a class=\"btn btn-large\" href" +
"=\"");


            
            #line 70 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
                                                  Write(Url.Action("Index", "Roster"));

            
            #line default
            #line hidden
WriteLiteral("\">Avbryt</a>\r\n                    </div>\r\n                </div>\r\n");


            
            #line 73 "..\..\Areas\V2\Views\Authentication\LogOn.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
