#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/AdminTasks/_Layout.cshtml")]
    public partial class _Areas_V2_Views_AdminTasks__Layout_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_AdminTasks__Layout_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
  
    Layout = "~/Areas/V2/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"lead\">\r\n    Installerad version: ");


            
            #line 6 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
                    Write(Html.GetAssemblyVersion());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <ul class=\"nav n" +
"av-pills\">\r\n            ");


            
            #line 12 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("Användare", "sprite-glyphicons_024_parents", "Users", Url.Action("Users")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 13 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("RavenDB", "sprite-glyphicons_140_database_lock", "Raven", Url.Action("Raven")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 14 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("Event Store", "sprite-glyphicons_141_database_plus", "EventStoreActions", Url.Action("EventStoreActions")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 15 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("E-post", "sprite-glyphicons_399_e-mail", "SendMail", Url.Action("SendMail")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 16 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("Adoptera", "sprite-glyphicons_024_parents", "Adopt", Url.Action("Adopt")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 17 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
       Write(Html.ActionMenuLink("Inställningar", "sprite-glyphicons_280_settings", "Features", Url.Action("Features")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n    </div>\r\n</div>\r\n\r\n");


            
            #line 22 "..\..\Areas\V2\Views\AdminTasks\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
