#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/AdminTasks/Users.cshtml")]
    public partial class _Areas_V2_Views_AdminTasks_Users_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<IEnumerable<UserViewModel>>
    {
        public _Areas_V2_Views_AdminTasks_Users_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
  
    ViewBag.Title = "Användare";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");


            
            #line 7 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<p>\r\n    ");


            
            #line 10 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
Write(Html.ActionLink("Skapa ny", "CreateUser"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table class=\"table table-condensed table-striped\">\r\n    <thead>\r\n       " +
" <tr>\r\n            <th>Namn</th>\r\n            <th>E-postadress</th>\r\n           " +
" <th>Status</th>\r\n            <th></th>\r\n        </tr>\r\n    </thead>\r\n\r\n    <tbo" +
"dy>\r\n");


            
            #line 23 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n                    ");


            
            #line 27 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
               Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    ");


            
            #line 30 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
               Write(Html.DisplayFor(modelItem => item.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    ");


            
            #line 33 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
                Write(item.IsActive ? "Aktiv" : "Inaktiv");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    ");


            
            #line 36 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
               Write(Html.ActionLink("Ta bort", "DeleteUser", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    | ");


            
            #line 37 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
                 Write(Html.ActionLink(item.IsActive ? "Inaktivera" : "Aktivera", "ActivateUser", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");


            
            #line 40 "..\..\Areas\V2\Views\AdminTasks\Users.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n");


        }
    }
}
#pragma warning restore 1591
