#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResultAdmin/RegisterMatch4Editor.cshtml")]
    public partial class _Areas_V2_Views_MatchResultAdmin_RegisterMatch4Editor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.MatchResultAdminController.RegisterMatch4ViewModel>
    {
        public _Areas_V2_Views_MatchResultAdmin_RegisterMatch4Editor_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("<div class=\"well well-small\">\r\n    ");


            
            #line 3 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
Write(Html.DisplayFor(x => x.RosterViewModel.Header));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


            
            #line 5 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
 using (Html.BeginForm(
    "RegisterMatch4Editor",
    "MatchResultAdmin",
    FormMethod.Post,
    new
    {
        @class = " quill-form",
        data_quill_data = new QuillData(
            Html.NameFor(x => x.Model.CommentaryHtml).ToString(),
            Html.NameFor(x => x.Model.Commentary).ToString(),
            "Skriv ett matchreferat...").ToJson()
    }))
{
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary"));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
                                                                            
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
Write(Html.EditorFor(x => x.Model, "Match4PostModel", new { Model.PlayerListItems }));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
                                                                                   

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"form-actions\">\r\n        <button class=\"btn btn-primary btn-large\"" +
" type=\"submit\">Registrera</button>\r\n        ");


            
            #line 22 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
   Write(Html.ActionLink("Avbryt", "Index", "MatchResult", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 24 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatch4Editor.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
