#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResultAdmin/Register.cshtml")]
    public partial class _Areas_V2_Views_MatchResultAdmin_Register_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.MatchResultAdminController.RegisterResult>
    {
        public _Areas_V2_Views_MatchResultAdmin_Register_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
  
    ViewBag.Title = ViewBag.Title ?? "Registrera matchresultat";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span8\">\r\n        <h4>");


            
            #line 8 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");


            
            #line 9 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
         using (Html.BeginForm("Register", "MatchResultAdmin", FormMethod.Post))
        {
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
       Write(Html.HiddenFor(model => model.AggregateId));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
                                                       

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"control-group\">\r\n                <label class=\"control-la" +
"bel\" for=\"rosterid\">Match:</label>\r\n                <div class=\"controls\">\r\n    " +
"                ");


            
            #line 15 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
               Write(Html.DropDownList("rosterid", (IEnumerable<SelectListItem>)ViewBag.rosterid, "Välj match", new { required = "required" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <span class=\"help-block\">Manuella resul" +
"tat stödjer än så länge enbart 4-mannamatcher.</span>\r\n            </div>\r\n");



WriteLiteral("            <div class=\"form-actions\">\r\n                <button class=\"btn btn-pr" +
"imary btn-large\" type=\"submit\">Välj</button>\r\n                ");


            
            #line 21 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
           Write(Html.ActionLink("Avbryt", "Index", "MatchResult", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 23 "..\..\Areas\V2\Views\MatchResultAdmin\Register.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
