#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResultAdmin/RegisterMatchEditor.cshtml")]
    public partial class _Areas_V2_Views_MatchResultAdmin_RegisterMatchEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.MatchResultAdminController.RegisterMatchViewModel>
    {
        public _Areas_V2_Views_MatchResultAdmin_RegisterMatchEditor_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<div class=""control-group"">
    <label class=""control-label"" for=""teamScore"">Lagpoäng:</label>
    <div class=""controls"">
        <input id=""teamScore""
               name=""teamScore""
               type=""text""
               pattern=""\d*""
               min=""0""
               max=""20""
               value=""");


            
            #line 12 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                 Write(Model.TeamScore);

            
            #line default
            #line hidden
WriteLiteral(@"""
               required=""required"" />
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""opponentScore"">Motståndarpoäng:</label>
    <div class=""controls"">
        <input id=""opponentScore""
               name=""opponentScore""
               type=""text""
               pattern=""\d*""
               min=""0""
               max=""20""
               value=""");


            
            #line 25 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                 Write(Model.OpponentScore);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n               required=\"required\" />\r\n    </div>\r\n</div>\r\n");


            
            #line 29 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
 for (var i = 0; i < Model.Series.Length; i++)
{

            
            #line default
            #line hidden
WriteLiteral(@"    <div class=""row"">
        <div class=""span8"">
            <table class=""table table-condensed table-bordered table-striped"">
                <tr>
                    <td>Namn</td>
                    <td>Banpoäng</td>
                    <td>Poäng</td>
                </tr>
                <tr>
                    <td colspan=""3"">Serie ");


            
            #line 40 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                                      Write(i + 1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 42 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                 for (var j = 0; j < Model.Series[i].Serie.Tables.Count; j++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td rowspan=\"2\">\r\n             " +
"               ");


            
            #line 46 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                       Write(Html.TextBoxFor(
                                m => m.Series[i].Serie.Tables[j].Score,
                                new
                                {
                                    required = "required",
                                    type = "number",
                                    pattern = @"\d*",
                                    min = "0",
                                    max = "1"
                                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");



WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   ");


            
            #line 60 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                       Write(Html.DropDownListFor(
                                m => m.Series[i].Serie.Tables[j].Game1.Player,
                                Model.PlayerListItems,
                                "Välj spelare"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          ");


            
            #line 66 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                       Write(Html.TextBoxFor(
                                m => m.Series[i].Serie.Tables[j].Game1.Pins,
                                new
                                {
                                    @class = "span1",
                                    required = "required",
                                    type = "number",
                                    pattern = @"\d*",
                                    min = "0",
                                    max = "300"
                                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");



WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   ");


            
            #line 81 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                       Write(Html.DropDownListFor(
                                m => m.Series[i].Serie.Tables[j].Game2.Player,
                                Model.PlayerListItems,
                                "Välj spelare"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          ");


            
            #line 87 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                       Write(Html.TextBoxFor(
                                m => m.Series[i].Serie.Tables[j].Game2.Pins,
                                new
                                {
                                    @class = "span1",
                                    required = "required",
                                    type = "number",
                                    pattern = @"\d*",
                                    min = "0",
                                    max = "300"
                                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");


            
            #line 100 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n    </div>\r\n");


            
            #line 104 "..\..\Areas\V2\Views\MatchResultAdmin\RegisterMatchEditor.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
