#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_V2_Views_Shared__Layout_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
  
    ViewBag.Title = "Snittlistan";


            
            #line default
            #line hidden
WriteLiteral(@"<!DOCTYPE html>
<html lang=""se"">
<head>
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""initial-scale=1.0,width=device-width"" />
    <meta name=""apple-mobile-web-app-capable"" content=""yes"" />
    <meta name=""apple-mobile-web-app-status-bar-style"" content=""black"" />
    <meta name=""apple-mobile-web-app-title"" content=""");


            
            #line 11 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                                Write(Tenant.WebAppTitle);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <meta name=\"google-site-verification\" content=\"g8KwkjfVGgtu5zxYGhIEfJS4" +
"JGVkCMS1YMdp5WNOOpU\" />\r\n    <link rel=\"icon\"\r\n          href=\"");


            
            #line 14 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak($"~/Content/css/images/{Tenant.Favicon}"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <link rel=\"apple-touch-icon\"\r\n          sizes=\"");


            
            #line 16 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Tenant.AppleTouchIconSize);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n          href=\"");


            
            #line 17 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak($"~/Content/css/images/{Tenant.AppleTouchIcon}"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <title>");


            
            #line 18 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n");


            
            #line 20 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link href=\"");


            
            #line 22 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/bootstrap/css/bootstrap.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");



WriteLiteral("        <link href=\"");


            
            #line 23 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/bootstrap/css/bootstrap-responsive.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");



WriteLiteral("        <link href=\"");


            
            #line 24 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/air-datepicker/datepicker.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");


            
            #line 25 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <link href=\"");


            
            #line 28 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/bootstrap/css/bootstrap.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");



WriteLiteral("        <link href=\"");


            
            #line 29 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/bootstrap/css/bootstrap-responsive.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");



WriteLiteral("        <link href=\"");


            
            #line 30 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Url.ContentCacheBreak("~/Content/external/air-datepicker/datepicker.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");


            
            #line 31 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <link href=\"");


            
            #line 32 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/external/quill/quill.snow.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <link href=\"");


            
            #line 33 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/css/glyphicons.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n\r\n    <link href=\"");


            
            #line 35 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/css/main.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <link href=\"");


            
            #line 36 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/css/checkbox.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <script src=\"");


            
            #line 37 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/js/GA.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 38 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
     if (User is object)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n        window.ChatraIntegration = {\r\n            name: \'");


            
            #line 42 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
              Write(User.CustomIdentity.Name);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            email: \'");


            
            #line 43 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(User.CustomIdentity.Email);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n        };\r\n        window.ChatraSetup = {\r\n            clientId: \'");


            
            #line 46 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                  Write(User.CustomIdentity.UniqueId);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n        };\r\n        </script>\r\n");


            
            #line 49 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script src=\"");


            
            #line 50 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/external/chatra/chatra.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""></script>
</head>
<body>
    <div class=""navbar"">
        <div class=""navbar-inner"">
            <div class=""container"">
                <button type=""button"" class=""btn btn-navbar"" data-toggle=""collapse"" data-target="".nav-collapse"">
                    <span class=""icon-bar""></span>
                    <span class=""icon-bar""></span>
                    <span class=""icon-bar""></span>
                </button>
                <a href=""");


            
            #line 61 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                    Write(Url.RouteUrl("V2_default", new { controller = "Roster", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"brand\">\r\n                    Snittlistan\r\n                </a>\r\n        " +
"        <div class=\"nav-collapse\" data-nav-collapse>\r\n                    ");


            
            #line 65 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
               Write(Html.Action("NavPart", "Layout"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <ul class=\"nav pull-right\">\r\n");


            
            #line 67 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                         if (Request.IsAuthenticated)
                        {

            
            #line default
            #line hidden
WriteLiteral(@"                            <li class=""dropdown"">
                                <button data-auth-menu-toggle class=""btn dropdown-toggle"" data-toggle=""dropdown"">
                                    <i class=""sprite-glyphicons_019_cogwheel""></i>
                                    <b class=""caret""></b>
                                </button>
                                <ul class=""dropdown-menu"">
");


            
            #line 75 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                     if (Request.IsAdmin(User))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>\r\n                                   " +
"         <a href=\"");


            
            #line 78 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                                Write(Url.Action("Index", "AdminTasks"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                                                <i class=""sprite-glyphicons_023_cogwheels""></i>
                                                Administration
                                            </a>
                                        </li>
");



WriteLiteral("                                        <li class=\"divider\"></li>\r\n");


            
            #line 84 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <li class=\"nav-header\">\r\n                    " +
"                    ");


            
            #line 86 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                    Write(User?.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>\r\n                                        <a href=\"");


            
            #line 89 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                            Write(Url.Action("Index", "UserProfile"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                                            <i class=""sprite-glyphicons_023_cogwheels""></i>
                                            Min profil
                                        </a>
                                    </li>
                                    <li>
                                        <a href=""");


            
            #line 95 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                            Write(Url.Action("LogOff", "Authentication"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                                            <i class=""sprite-glyphicons_203_lock""></i>
                                            Logga ut
                                        </a>
                                    </li>
                                </ul>
                            </li>
");


            
            #line 102 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a href=\"");


            
            #line 106 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                                    Write(Url.Action("LogOn", "Authentication"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    <i class=\"sprite-glyphicons_204_unlock\"><" +
"/i>\r\n                                    Logga in\r\n                             " +
"   </a>\r\n                            </li>\r\n");


            
            #line 111 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n    </div>\r\n    <div id=\"main\" class=\"container\">\r\n        ");


            
            #line 118 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
   Write(Html.Partial("Flash"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 119 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <script id=\"dsq-count-scr\" src=\"//snittlistan.disqus.com/count." +
"js\" async></script>\r\n    <script>\r\n        var logErrorUrl = \'");


            
            #line 123 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                      Write(Url.Action("LogJavaScriptError", "Error"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n");


            
            #line 125 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script src=\"");


            
            #line 127 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/jquery/jquery-3.3.1.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 128 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/bootstrap/js/bootstrap.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 129 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/air-datepicker/datepicker.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 130 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/quill/quill.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 131 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script src=\"");


            
            #line 134 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/jquery/jquery-3.3.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 135 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/bootstrap/js/bootstrap.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 136 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/air-datepicker/datepicker.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");



WriteLiteral("        <script src=\"");


            
            #line 137 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
                Write(Url.ContentCacheBreak("~/Content/external/quill/quill.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


            
            #line 138 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script src=\"");


            
            #line 139 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/external/waypoints/waypoints-0.0.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script src=\"");


            
            #line 140 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/js/stacktrace.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script src=\"");


            
            #line 141 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/js/helpers/typeahead.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script src=\"");


            
            #line 142 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/js/QuillForm.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script src=\"");


            
            #line 143 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
            Write(Url.ContentCacheBreak("~/Content/js/Layout.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    ");


            
            #line 144 "..\..\Areas\V2\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
