#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Shared/NotFound.cshtml")]
    public partial class _Areas_V2_Views_Shared_NotFound_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_Shared_NotFound_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
  
    ViewBag.Title = "Sidan hittades ej";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>");


            
            #line 5 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n<p>Kunde inte hitta sidan: ");


            
            #line 6 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
                      Write(ViewBag.RequestedUrl);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 7 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
 if (ViewBag.ReferrerUrl != null) {

            
            #line default
            #line hidden
WriteLiteral("<p>Gå tillbaka till <a href=\"");


            
            #line 8 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
                        Write(ViewBag.ReferrerUrl);

            
            #line default
            #line hidden
WriteLiteral("\">föregående sidan</a>.</p>\r\n");


            
            #line 9 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
}


            
            #line default
            #line hidden

            
            #line 12 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
                                         

            
            #line default
            #line hidden

            
            #line 13 "..\..\Areas\V2\Views\Shared\NotFound.cshtml"
Write(new string(' ', 512));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
