#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/_Register.cshtml")]
    public partial class _Areas_V2_Views_Roster__Register_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_Roster__Register_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V2\Views\Roster\_Register.cshtml"
 if (User.IsInRole2(WebsiteRoles.Uk.UkTasks))
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"row\">\r\n        <div class=\"span6 admin\">\r\n            <a href=\"");


            
            #line 5 "..\..\Areas\V2\Views\Roster\_Register.cshtml"
                Write(Url.Action("CreateBits"));

            
            #line default
            #line hidden
WriteLiteral("\">");



WriteLiteral("\r\n                <i class=\"sprite-glyphicons_358_file_import\"></i>\r\n            " +
"    Lägg till från BITS\r\n            </a>\r\n            <a href=\"");


            
            #line 9 "..\..\Areas\V2\Views\Roster\_Register.cshtml"
                Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <i class=\"sprite-glyphicons_030_pencil\"></i>\r\n               " +
" Lägg till match manuellt\r\n            </a>\r\n        </div>\r\n    </div>\r\n");


            
            #line 15 "..\..\Areas\V2\Views\Roster\_Register.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
