#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    
    #line 1 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
    using Snittlistan.Web.Models;
    
    #line default
    #line hidden
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/_RosterEditor.cshtml")]
    public partial class _Areas_V2_Views_Roster__RosterEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.RosterController.CreateRosterViewModel>
    {
        public _Areas_V2_Views_Roster__RosterEditor_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral(@"
<div class=""control-group"">
    <label class=""control-label"" for=""season"">Säsong:</label>
    <div class=""controls"">
        <input type=""text""
               id=""season""
               name=""season""
               placeholder=""Säsong""
               autofocus=""autofocus""
               title=""Ange säsong""
               pattern=""\d*""
               required=""required""
               value=""");


            
            #line 15 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                 Write(Model.Season);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <span class=\"help-block\">\r\n            Ange säsongen för matchen. S" +
"kriv första delen av säsongen, t.ex. <strong>");


            
            #line 17 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                                                                                Write(Model.Season);

            
            #line default
            #line hidden
WriteLiteral("</strong>&minus;");


            
            #line 17 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                                                                                                              Write(Model.Season + 1);

            
            #line default
            #line hidden
WriteLiteral(".\r\n            Vanligtvis är det redan rätt ifyllt.\r\n        </span>\r\n    </div>\r" +
"\n</div>\r\n<div class=\"control-group\">\r\n    <label class=\"control-label\" for=\"turn" +
"\">Omgång:</label>\r\n    <div class=\"controls\">\r\n        <select id=\"turn\" name=\"t" +
"urn\">\r\n");


            
            #line 26 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
             for (var i = 1; i <= 25; i++)
            {
                if (Model.Turn == i)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option selected>");


            
            #line 30 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                                Write(i);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 31 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option>");


            
            #line 34 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                       Write(i);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 35 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </select>
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""bitsMatchId"">BITS Match Id:</label>
    <div class=""controls"">
        <input type=""text""
               id=""bitsMatchId""
               name=""bitsMatchId""
               placeholder=""BITS Match Id""
               title=""Ange match id""
               pattern=""\d*""
               required=""required""
               readonly=""readonly""
               value=""");


            
            #line 51 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                 Write(Model.BitsMatchId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    <label class=\"control-" +
"label\" for=\"team\">Lag:</label>\r\n    <div class=\"controls\">\r\n        <select id=\"" +
"team\" name=\"team\">\r\n");


            
            #line 58 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
             foreach (WebsiteConfig.TeamNameAndLevel nameAndLevel in ViewBag.TeamNamesAndLevels)
            {

            
            #line default
            #line hidden
WriteLiteral("                <option value=\"");


            
            #line 60 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                          Write(nameAndLevel.FormattedForOption);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n");


            
            #line 61 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                         if (nameAndLevel.TeamName == Model.Team) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" selected=\"selected\" ");

WriteLiteral(" ");


            
            #line 61 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                                                                                                       }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                    ");


            
            #line 62 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
               Write(nameAndLevel.TeamName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </option>\r\n");


            
            #line 64 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    <div clas" +
"s=\"controls\">\r\n        <label class=\"checkbox\">\r\n            ");


            
            #line 71 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
       Write(Html.EditorFor(model => model.IsFourPlayer));

            
            #line default
            #line hidden
WriteLiteral(@" 4-manna
        </label>
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""opponent"">Motståndare:</label>
    <div class=""controls"">
        <input type=""text""
               id=""opponent""
               name=""opponent""
               placeholder=""Motståndare""
               autocorrect=""off""
               autocomplete=""off""
               spellcheck=""false""
               value=""");


            
            #line 85 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                 Write(Model.Opponent);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n               required\r\n               data-enabletypeahead=\"yes\"\r\n          " +
"     data-url=\"/search/opponents\" />\r\n    </div>\r\n</div>\r\n<div class=\"control-gr" +
"oup\">\r\n    ");


            
            #line 92 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
Write(Html.LabelFor(x => x.Date, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        ");


            
            #line 94 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
   Write(Html.TextBoxFor(
            x => x.Date,
            new
            {
                @class = "date-picker",
                @readonly = "readonly",
                required = "required",
                placeholder = "Välj datum",
                data_datepicker = "",
                data_timepicker = "true"
            }));

            
            #line default
            #line hidden
WriteLiteral(@"
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""location"">Plats:</label>
    <div class=""controls"">
        <input type=""text""
               id=""location""
               name=""location""
               placeholder=""Bowlinghall""
               autocorrect=""off""
               autocomplete=""off""
               spellcheck=""false""
               value=""");


            
            #line 117 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                 Write(Model.Location);

            
            #line default
            #line hidden
WriteLiteral(@"""
               required
               data-enabletypeahead=""yes""
               data-url=""/search/locations"" />
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""oilPatternName"">Oljeprofil:</label>
    <div class=""controls"">
        <input type=""text""
               id=""oilPatternName""
               name=""oilPatternName""
               placeholder=""Oljeprofil""
               autocorrect=""off""
               autocomplete=""off""
               spellcheck=""false""
");


            
            #line 133 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                if (Model.BitsMatchId != 0) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" readonly=\"readonly\" ");

WriteLiteral("  ");


            
            #line 133 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                                                                                  }

            
            #line default
            #line hidden
WriteLiteral("               value=\"");


            
            #line 134 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
                 Write(Model.OilPatternName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n               data-enabletypeahead=\"yes\"\r\n               data-url=\"/search/oi" +
"lpattern\" />\r\n        ");


            
            #line 137 "..\..\Areas\V2\Views\Roster\_RosterEditor.cshtml"
   Write(Html.HiddenFor(x => x.OilPatternUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
