#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/Absences.cshtml")]
    public partial class _Areas_V2_Views_Roster_Absences_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<IEnumerable<Snittlistan.Web.Areas.V2.Indexes.AbsenceIndex.Result>>
    {
        public _Areas_V2_Views_Roster_Absences_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"
<div class=""row"">
    <div class=""span6"">
        <h5>Anmäld frånvaro</h5>
    </div>
</div>
<div class=""row"">
    <div class=""span8"">
        <table class=""table table-condensed table-striped"">
            <tr>
                <th>Namn</th>
                <th></th>
            </tr>
");


            
            #line 15 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
             foreach (var absence in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 18 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
                   Write(absence.PlayerName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>\r\n                        <time datetime=\"");


            
            #line 20 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
                                   Write(absence.From.ToString("s"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 20 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
                                                                Write(absence.From.ToString("d MMM"));

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n                        &minus;\r\n                        <time datetime=" +
"\"");


            
            #line 22 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
                                   Write(absence.To.ToString("s"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 22 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
                                                              Write(absence.To.ToString("d MMM"));

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n                    </td>\r\n                </tr>\r\n");


            
            #line 25 "..\..\Areas\V2\Views\Roster\Absences.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
