#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/CreateBits.cshtml")]
    public partial class _Areas_V2_Views_Roster_CreateBits_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<dynamic>
    {
        public _Areas_V2_Views_Roster_CreateBits_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div class=\"row\">\r\n    <div class=\"span8\">\r\n        <h4>Lägg till schemalagd matc" +
"h från BITS</h4>\r\n        <form class=\"form-horizontal\" method=\"POST\" action=\"");


            
            #line 4 "..\..\Areas\V2\Views\Roster\CreateBits.cshtml"
                                                       Write(Url.Action("CreateBitsVerify"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 5 "..\..\Areas\V2\Views\Roster\CreateBits.cshtml"
       Write(Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary"));

            
            #line default
            #line hidden
WriteLiteral(@"
            <div class=""control-group"">
                <label class=""control-label"" for=""bitsMatchId"">BITS Match Id:</label>
                <div class=""controls"">
                    <input id=""bitsMatchId""
                           name=""bitsMatchId""
                           type=""text""
                           autofocus=""autofocus""
                           pattern=""\d*""
                           title=""Ange matchnumret från BITS""
                           required=""required"" />
                </div>
            </div>
            <div class=""form-actions"">
                <button class=""btn btn-primary btn-large"" type=""submit"">Verifiera</button>
                ");


            
            #line 20 "..\..\Areas\V2\Views\Roster\CreateBits.cshtml"
           Write(Html.ActionLink("Avbryt", "Index", "Roster", null, new { @class = "btn btn-large" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
