#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/Print.cshtml")]
    public partial class _Areas_V2_Views_Roster_Print_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<ViewTurnViewModel>
    {
        public _Areas_V2_Views_Roster_Print_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\Roster\Print.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <link href=\"https://netdna.bootstrapcdn.com/" +
"twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css\" rel=\"stylesheet\" />\r\n   " +
" <link rel=\"stylesheet\" href=\"");


            
            #line 8 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                            Write(Url.Content("~/Content/css/print.css"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
    <style>
        body {
            padding-top: 1cm;
        }

        header {
            position: relative;
            height: 2cm;
        }

        img.header-image-left {
            height: 100%;
            position: absolute;
            left: 0;
        }

        h1.top-title {
            position: absolute;
            left: 50%;
            -ms-transform: translateX(-50%);
            -webkit-transform: translateX(-50%);
            transform: translateX(-50%);
        }

        img.header-image-right {
            height: 100%;
            position: absolute;
            right: 0;
        }

        div.row {
            padding-top: 0.5cm;
        }
    </style>
</head>
<body>
    <div class=""container"">
        <div class=""row"">
            <header>
                <img class=""header-image-left"" src=""~/Content/css/images/");


            
            #line 48 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                                                                    Write(Model.HeaderImagePath);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                <h1 class=\"top-title\">Omgång ");


            
            #line 49 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                                        Write(Model.Turn);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                <img class=\"header-image-right \" src=\"~/Content/css/images" +
"/");


            
            #line 50 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                                                                      Write(Model.HeaderImagePath);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </header>\r\n        </div>\r\n");


            
            #line 53 "..\..\Areas\V2\Views\Roster\Print.cshtml"
          
            var start = 0;
            while (true)
            {
                var rosters = Model.RosterViewModels.Skip(start).Take(2).ToArray();
                if (rosters.Length == 0)
                {
                    break;
                }


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"row\" style=\"page-break-after: always;\">\r\n");


            
            #line 64 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                      
                        var style = new[]
                        {
                            "width: 45%; float: left; margin-right: 0.5cm;",
                            "width: 45%; float: right;"
                        };
                    

            
            #line default
            #line hidden

            
            #line 71 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                     for (var i = 0; i < rosters.Length; i++)
                    {
                        var roster = rosters[i];

            
            #line default
            #line hidden
WriteLiteral("                        <div style=\"");


            
            #line 74 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                               Write(style[i]);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 75 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                       Write(Html.DisplayFor(model => roster, "RosterViewModel", new
                            {
                                hideControls = true
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 79 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                       Write(Html.DisplayFor(model => roster, "Players", new
                            {
                                hideControls = true
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");


            
            #line 84 "..\..\Areas\V2\Views\Roster\Print.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 86 "..\..\Areas\V2\Views\Roster\Print.cshtml"

                start += rosters.Length;
            }
        

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 91 "..\..\Areas\V2\Views\Roster\Print.cshtml"
         if (Model.WithAbsence)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"row\">\r\n                <div class=\"span12\">\r\n            " +
"        <h2>Anmäld frånvaro</h2>\r\n                </div>\r\n            </div>\r\n");


            
            #line 98 "..\..\Areas\V2\Views\Roster\Print.cshtml"
            
            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\V2\Views\Roster\Print.cshtml"
       Write(Html.Action("AbsenceTable", "Absence", new
            {
                hideControls = true
            }));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\V2\Views\Roster\Print.cshtml"
              
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
