#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\V2\Views\Roster\View.cshtml"
    using Raven.Abstractions;
    
    #line default
    #line hidden
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/View.cshtml")]
    public partial class _Areas_V2_Views_Roster_View_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<ViewTurnViewModel>
    {
        public _Areas_V2_Views_Roster_View_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <h1 class=\"pull-left\">Omgå" +
"ng ");


            
            #line 6 "..\..\Areas\V2\Views\Roster\View.cshtml"
                                Write(Model.Turn);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 7 "..\..\Areas\V2\Views\Roster\View.cshtml"
         if (User.IsInRole2(WebsiteRoles.Uk.UkTasks))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"pull-right\">\r\n");


            
            #line 10 "..\..\Areas\V2\Views\Roster\View.cshtml"
                 using (Html.BeginForm(
                    "Print",
                    "Roster",
                    new { Model.Season, Model.Turn },
                    FormMethod.Post,
                    new { id = "printForm" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"print-options-container\">\r\n                      " +
"  <div class=\"print-option\">\r\n                            <label for=\"ExcludePas" +
"t\">\r\n                                ");


            
            #line 20 "..\..\Areas\V2\Views\Roster\View.cshtml"
                           Write(Html.CheckBox("ExcludePast", true));

            
            #line default
            #line hidden
WriteLiteral(" Utan passerade matcher\r\n                            </label>\r\n                  " +
"      </div>\r\n                        <div class=\"print-option\">\r\n              " +
"              <label for=\"ExcludePreliminary\">\r\n                                " +
"");


            
            #line 25 "..\..\Areas\V2\Views\Roster\View.cshtml"
                           Write(Html.CheckBox("ExcludePreliminary", true));

            
            #line default
            #line hidden
WriteLiteral(" Utan preliminära matcher\r\n                            </label>\r\n                " +
"        </div>\r\n                        <div class=\"print-option\">\r\n            " +
"                <label for=\"WithAbsence\">\r\n                                ");


            
            #line 30 "..\..\Areas\V2\Views\Roster\View.cshtml"
                           Write(Html.CheckBox("WithAbsence", true));

            
            #line default
            #line hidden
WriteLiteral(" Med frånvaro\r\n                            </label>\r\n                        </di" +
"v>\r\n                        <div class=\"print-option\">\r\n                        " +
"    <label for=\"Pdf\">\r\n                                ");


            
            #line 35 "..\..\Areas\V2\Views\Roster\View.cshtml"
                           Write(Html.CheckBox("Pdf", false));

            
            #line default
            #line hidden
WriteLiteral(" Skapa pdf\r\n                            </label>\r\n                        </div>\r" +
"\n                    </div>\r\n");



WriteLiteral(@"                    <div class=""print-links-container"">
                        <button class=""btn btn-secondary btn-small"" type=""submit"">
                            <i class=""sprite-glyphicons_015_print""></i>
                            Utskrift
                        </button>
                    </div>
");


            
            #line 45 "..\..\Areas\V2\Views\Roster\View.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");


            
            #line 47 "..\..\Areas\V2\Views\Roster\View.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"clearfix\"></div>\r\n    </div>\r\n</div>\r\n\r\n");


            
            #line 52 "..\..\Areas\V2\Views\Roster\View.cshtml"
   
    int n = Model.RosterViewModels.Count(x =>
        x.Players.Find(y => y.PlayerId == User.CustomIdentity.PlayerId)?.Accepted == false);


            
            #line default
            #line hidden

            
            #line 56 "..\..\Areas\V2\Views\Roster\View.cshtml"
 if (User.CustomIdentity.PlayerId != null && Model.RosterViewModels.Any(x =>
    x.Preliminary == false
    && x.Header.Date.ToUniversalTime() > SystemTime.UtcNow
    && n > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"row\">\r\n        <div class=\"span12\">\r\n            <div class=\"aler" +
"t alert-success\">\r\n");


            
            #line 64 "..\..\Areas\V2\Views\Roster\View.cshtml"
                 if (n > 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <strong>Du är uttagen i ");


            
            #line 66 "..\..\Areas\V2\Views\Roster\View.cshtml"
                                       Write(n);

            
            #line default
            #line hidden
WriteLiteral(" matcher!</strong> ");



WriteLiteral("Vänligen bekräfta nedan.");

WriteLiteral("\r\n");


            
            #line 67 "..\..\Areas\V2\Views\Roster\View.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <strong>Du är uttagen!</strong> ");



WriteLiteral("Vänligen bekräfta nedan.");

WriteLiteral("\r\n");


            
            #line 71 "..\..\Areas\V2\Views\Roster\View.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 75 "..\..\Areas\V2\Views\Roster\View.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 77 "..\..\Areas\V2\Views\Roster\View.cshtml"
  
    var start = 0;
    var rosters = Model.RosterViewModels.Skip(start).Take(3).ToList();


            
            #line default
            #line hidden

            
            #line 81 "..\..\Areas\V2\Views\Roster\View.cshtml"
 while (rosters.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"row\">\r\n");


            
            #line 84 "..\..\Areas\V2\Views\Roster\View.cshtml"
         foreach (var roster in rosters)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"span4\">\r\n                ");


            
            #line 87 "..\..\Areas\V2\Views\Roster\View.cshtml"
           Write(Html.DisplayFor(model => roster, "RosterViewModel", new { hideControls = true }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 88 "..\..\Areas\V2\Views\Roster\View.cshtml"
           Write(Html.DisplayFor(model => roster, "Players"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 90 "..\..\Areas\V2\Views\Roster\View.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 92 "..\..\Areas\V2\Views\Roster\View.cshtml"

    start += 3;
    rosters = Model.RosterViewModels.Skip(start).Take(3).ToList();
}

            
            #line default
            #line hidden

            
            #line 96 "..\..\Areas\V2\Views\Roster\View.cshtml"
 if (User.IsInRole2(WebsiteRoles.Uk.UkTasks))
{
    
            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\V2\Views\Roster\View.cshtml"
Write(Html.Action("PlayerStatus", new
    {
        turn = Model.Turn,
        season = Model.Season
    }));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\V2\Views\Roster\View.cshtml"
      
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
