#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V1/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_V1_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_V1_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n    <title>");


            
            #line 5 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    ");


            
            #line 6 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Favicon(Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Css(CssType.Blitzer));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Css("Site.css", Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--[if lt IE 9]><script src=\"https://html5shim.googlecode.com/svn/trunk/ht" +
"ml5.js\"></script><![endif]-->\r\n");



WriteLiteral("\r\n    ");



WriteLiteral("\r\n</head>\r\n<body>\r\n    <div class=\"page\">\r\n        <header>\r\n            <div id=" +
"\"title\">\r\n                <h1>");


            
            #line 17 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
               Write(Html.ActionLink("Snittlistan", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            </div>\r\n            <div id=\"logindisplay\">\r\n                ");


            
            #line 20 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LogOnPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <nav>\r\n                <ul id=\"menu\">\r\n        " +
"            <li>");


            
            #line 24 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Matcher", "Index", "Match"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");


            
            #line 25 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink("Om", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>\r\n                        <a href=\"");


            
            #line 27 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
                            Write(Url.Action("Index", "Roster", new { area = "V2" }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Tillbaka till nuvarande säsong\r\n                 " +
"       </a>\r\n                    </li>\r\n                </ul>\r\n            </nav" +
">\r\n        </header>\r\n        <section id=\"main\">\r\n            ");


            
            #line 35 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </section>\r\n        <footer>\r\n            ");


            
            #line 38 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
       Write(RenderSection("footer", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </footer>\r\n    </div>\r\n    <div id=\"feedbackTab\"></div>\r\n    ");


            
            #line 42 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Script(ScriptType.JQuery));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 43 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Script(ScriptType.Modernizr));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 44 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Script(ScriptType.JQueryUI));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 45 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(Content.Script(ScriptType.JQueryUII18N));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        var logErrorUrl = \'");


            
            #line 47 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
                      Write(Url.Action("LogJavaScriptError", "Error"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(function() {\r\n            window.Waypoints.debug(true).intercept(\'a" +
"\');\r\n        });\r\n    </script>\r\n    <link href=\"");


            
            #line 52 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/js/stacktrace.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <link href=\"");


            
            #line 53 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/js/feedback.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <link href=\"");


            
            #line 54 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/js/button.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    <link href=\"");


            
            #line 55 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
           Write(Url.ContentCacheBreak("~/Content/external/waypoints/waypoints-0.0.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n    ");


            
            #line 56 "..\..\Areas\V1\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
