#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V1/Views/Shared/_LogOnPartial.cshtml")]
    public partial class _Areas_V1_Views_Shared__LogOnPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_V1_Views_Shared__LogOnPartial_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
 if (Request.IsAuthenticated)
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("Välkommen <strong>");


            
            #line 3 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
                       Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>! [ ");


            
            #line 3 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
                                                       Write(Html.ActionLink("Logga ut", "LogOff", "Account"));

            
            #line default
            #line hidden
WriteLiteral(" ]");

WriteLiteral("\r\n");


            
            #line 4 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("[ ");


            
            #line 7 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
   Write(Html.ActionLink("Logga in", "LogOn", "Account"));

            
            #line default
            #line hidden
WriteLiteral(" ]\r\n");


            
            #line 8 "..\..\Areas\V1\Views\Shared\_LogOnPartial.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
