#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/UserProfile/Index.cshtml")]
    public partial class _Areas_V2_Views_UserProfile_Index_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.UserProfileController.UserSettingsViewModel>
    {
        public _Areas_V2_Views_UserProfile_Index_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n");


            
            #line 5 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
         using (Html.BeginForm(
            "Save",
            "UserProfile",
            FormMethod.Post,
            new
            {
                @class = "form-horizontal"
            }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <fieldset>\r\n                <legend>Notifieringar genom e-post</legen" +
"d>\r\n            </fieldset>\r\n");



WriteLiteral("            <div class=\"control-group\">\r\n                ");


            
            #line 18 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
           Write(Html.LabelFor(x => x.RosterMailEnabled, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div class=\"controls\">\r\n                    ");


            
            #line 20 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
               Write(Html.CheckBoxFor(x => x.RosterMailEnabled, new { @class = "switch" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span class=\"help-block\">\r\n                        Få e-pos" +
"t vid uppdaterad laguttagning.\r\n                    </span>\r\n                </d" +
"iv>\r\n            </div>\r\n");



WriteLiteral("            <div class=\"control-group\">\r\n                ");


            
            #line 27 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
           Write(Html.LabelFor(x => x.AbsenceMailEnabled, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div class=\"controls\">\r\n                    ");


            
            #line 29 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
               Write(Html.CheckBoxFor(x => x.AbsenceMailEnabled, new { @class = "switch" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span class=\"help-block\">\r\n                        Få e-pos" +
"t vid registrerad frånvaro.\r\n                    </span>\r\n                </div>" +
"\r\n            </div>\r\n");



WriteLiteral("            <div class=\"control-group\">\r\n                ");


            
            #line 36 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
           Write(Html.LabelFor(x => x.MatchResultMailEnabled, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div class=\"controls\">\r\n                    ");


            
            #line 38 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
               Write(Html.CheckBoxFor(x => x.MatchResultMailEnabled, new { @class = "switch" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span class=\"help-block\">\r\n                        Få e-pos" +
"t när match-resultat registreras.\r\n                    </span>\r\n                " +
"</div>\r\n            </div>\r\n");



WriteLiteral("            <div class=\"control-group\">\r\n                <div class=\"controls\">\r\n" +
"                    <button class=\"btn btn-primary btn-large\" type=\"submit\">Spar" +
"a</button>\r\n                </div>\r\n            </div>\r\n");


            
            #line 49 "..\..\Areas\V2\Views\UserProfile\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
