#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/ActivityIndex/Index.cshtml")]
    public partial class _Areas_V2_Views_ActivityIndex_Index_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.ActivityIndexController.IndexViewModel>
    {
        public _Areas_V2_Views_ActivityIndex_Index_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <h4>Träningsaktiviteter oc" +
"h träffar</h4>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r" +
"\n        <a href=\"");


            
            #line 10 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
            Write(Url.Action("Create", "ActivityEdit"));

            
            #line default
            #line hidden
WriteLiteral(@""">
            <i class=""sprite-glyphicons_030_pencil""></i>
            Lägg till aktivitet
        </a>
    </div>
</div>
<div class=""row"">
    <div class=""span12"">
        <table class=""table table-condensed table-striped"">
            <thead>
                <tr>
                    <th>Aktivitet</th>
                    <th>Datum</th>
                    <th>Text</th>
                    <th colspan=""2"">Redigera</th>
                </tr>
            </thead>
            <tbody>
");


            
            #line 28 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                 foreach (var item in Model.Items)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td rowspan=\"3\">\r\n             " +
"               ");


            
            #line 32 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                       Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td rowspan=\"3\">\r\n      " +
"                      <time datetime=\"");


            
            #line 35 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                                       Write(item.Date.ToString("s"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 36 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                           Write(item.Date.ToString("dddd d MMMM HH:mm"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </time>\r\n                        </td>\r\n           " +
"             <td rowspan=\"3\">\r\n                            <div class=\"cropped-m" +
"essage-free\">\r\n                                ");


            
            #line 41 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                           Write(item.MessageHtml);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </td>\r\n            " +
"            <td>\r\n                            ");


            
            #line 45 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                       Write(Html.ActionLink("Redigera", "Edit", "ActivityEdit", new { item.Id }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");



WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   ");


            
            #line 50 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                       Write(Html.ActionLink("Ta bort", "Delete", "ActivityEdit", new { item.Id }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");



WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   ");


            
            #line 55 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                       Write(Html.ActionLink("Visa", "Index", "ActivityDetails", null, null, "disqus_thread", new { item.Id }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");


            
            #line 58 "..\..\Areas\V2\Views\ActivityIndex\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
