#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Roster/DisplayTemplates/IndexHeader.cshtml")]
    public partial class _Areas_V2_Views_Roster_DisplayTemplates_IndexHeader_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.RosterController.InitialDataViewModel>
    {
        public _Areas_V2_Views_Roster_DisplayTemplates_IndexHeader_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");



WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12 index-top-links\">\r\n");


            
            #line 6 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
         if (Model.IsFiltered)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"show-all-matches-container\">\r\n                <a href=\"");


            
            #line 9 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
                    Write(Url.Action("Index", new
                         {
                             season = Model.SeasonStart
                         }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <i class=\"sprite-glyphicons_027_search\"></i>\r\n           " +
"         <span class=\"link-text\">Visa alla matcher</span>\r\n                    <" +
"small>Tidigare matcher är filtrerade</small>\r\n                </a>\r\n            " +
"</div>\r\n");


            
            #line 18 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"add-calendar-container\">\r\n            <a href=\"");


            
            #line 21 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
                Write(Url.GetWebcalUrl());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <i class=\"sprite-glyphicons_045_calendar\"></i>\r\n             " +
"   Lägg till i din kalender\r\n            </a>\r\n        </div>\r\n    </div>\r\n</div" +
">\r\n\r\n");


            
            #line 29 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
 if (User?.IsInRole2(WebsiteRoles.Activity.Manage) ?? false)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"row\">\r\n        <div class=\"span12\">\r\n            ");


            
            #line 33 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
       Write(Html.ActionLink("Hantera aktiviteter", "Index", "ActivityIndex"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");


            
            #line 36 "..\..\Areas\V2\Views\Roster\DisplayTemplates\IndexHeader.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<hr />\r\n");


        }
    }
}
#pragma warning restore 1591
