#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResult/_BitsSerieEditor.cshtml")]
    public partial class _Areas_V2_Views_MatchResult__BitsSerieEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<RegisterSerie>
    {
        public _Areas_V2_Views_MatchResult__BitsSerieEditor_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<table class=\"table table-condensed table-bordered table-striped\">\r\n    <tr>\r\n " +
"       <td>Namn</td>\r\n        <td>Banpoäng</td>\r\n        <td>Poäng</td>\r\n       " +
" <td>X</td>\r\n        <td>/</td>\r\n    </tr>\r\n");


            
            #line 11 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
     for (var i = 0; i < Model.Serie.Tables.Count; i++)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>\r\n                ");


            
            #line 15 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.DropDownListFor(
                    m => m.Serie.Tables[i].Game1.Player,
                    Model.Players,
                    "Välj spelare"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td rowspan=\"2\">\r\n                ");


            
            #line 21 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Score,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "1"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 34 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game1.Pins,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "300"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 47 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game1.Strikes,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "12"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 60 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game1.Spares,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "10"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");



WriteLiteral("        <tr>\r\n            <td>\r\n                ");


            
            #line 75 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.DropDownListFor(
                    m => m.Serie.Tables[i].Game2.Player,
                    Model.Players,
                    "Välj spelare"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 81 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game2.Pins,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "300"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 94 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game2.Strikes,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "12"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 107 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
           Write(Html.TextBoxFor(
                    m => m.Serie.Tables[i].Game2.Spares,
                    new
                    {
                        @class = "span1",
                        required = "required",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "10"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");


            
            #line 120 "..\..\Areas\V2\Views\MatchResult\_BitsSerieEditor.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");


        }
    }
}
#pragma warning restore 1591
