#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    
    #line 1 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
    using Snittlistan.Web.Areas.V2.Domain;
    
    #line default
    #line hidden
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResult/_MedalsEditor.cshtml")]
    public partial class _Areas_V2_Views_MatchResult__MedalsEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<EditMedalsViewModel>
    {
        public _Areas_V2_Views_MatchResult__MedalsEditor_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<div class=\"control-group\">\r\n    <label class=\"control-label\" for=\"eliteMedal\">" +
"Har medalj:</label>\r\n    <div class=\"controls\">\r\n        <select name=\"eliteMeda" +
"l\" id=\"eliteMedal\">\r\n");


            
            #line 8 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
             foreach (var enumValue in Enum.GetValues(typeof(EliteMedals.EliteMedal.EliteMedalValue)))
            {
                var desc = EliteMedals.EliteMedal.GetDescription((Enum)enumValue);
                if (string.IsNullOrEmpty(desc))
                {
                    desc = "Ingen medalj";
                }


            
            #line default
            #line hidden
WriteLiteral("                <option value=\"");


            
            #line 16 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                          Write(enumValue.ToString());

            
            #line default
            #line hidden
WriteLiteral("\"\r\n");


            
            #line 17 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                         if (Model.ExistingMedal == (EliteMedals.EliteMedal.EliteMedalValue)enumValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral(" selected=\"selected\" ");

WriteLiteral("\r\n");


            
            #line 20 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                        }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                    ");


            
            #line 21 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
               Write(desc);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </option>\r\n");


            
            #line 23 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </select>
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""capturedSeason"">Säsong:</label>
    <div class=""controls"">
        <input type=""text""
               name=""capturedSeason""
               id=""capturedSeason""
               value=""");


            
            #line 33 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                 Write(Model.CapturedSeason);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n               pattern=\"\\d*\"\r\n               title=\"Ange säsong, t.ex. ");


            
            #line 35 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                                    Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n               required />\r\n        <span class=\"help-block\">\r\n            Ang" +
"e säsongen då medaljen uppnåddes. Skriv första delen av säsongen, t.ex. <strong>" +
"");


            
            #line 38 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                                                                                          Write(Model.CurrentSeason);

            
            #line default
            #line hidden
WriteLiteral("</strong>&minus;");


            
            #line 38 "..\..\Areas\V2\Views\MatchResult\_MedalsEditor.cshtml"
                                                                                                                               Write(Model.CurrentSeason + 1);

            
            #line default
            #line hidden
WriteLiteral(".\r\n            Vanligtvis är det redan rätt ifyllt.\r\n        </span>\r\n    </div>\r" +
"\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
