#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Layout/NavPart.cshtml")]
    public partial class _Areas_V2_Views_Layout_NavPart_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Models.WebsiteConfig>
    {
        public _Areas_V2_Views_Layout_NavPart_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n<ul class=\"nav\">\r\n    ");


            
            #line 8 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
Write(Content.ControllerMenuLink(Html, "Omgångar", "sprite-glyphicons_045_calendar", "Roster", Url.Action("Index", "Roster")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 9 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
Write(Content.ControllerMenuLink(Html, "Resultat", "sprite-glyphicons_040_stats", "MatchResult", Url.Action("Index", "MatchResult")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 10 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
Write(Content.ControllerMenuLink(Html, "Frånvaro", "sprite-glyphicons_045_calendar", "Absence", Url.Action("Index", "Absence")));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 11 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
Write(Content.ControllerMenuLink(Html, "Medlemmar", "sprite-glyphicons_043_group", "Player", Url.Action("Index", "Player")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 12 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
     if (Model.HasV1)
    {
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
   Write(Content.ControllerMenuLink(
            Html,
            "2011-2012",
            "sprite-glyphicons_090_table",
            "Home",
            Url.Action(
                "Index",
                "Home",
                new
                {
                    area = "V1"
                })));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\V2\Views\Layout\NavPart.cshtml"
                   
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


        }
    }
}
#pragma warning restore 1591
