#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
    using Raven.Abstractions;
    
    #line default
    #line hidden
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Shared/DisplayTemplates/ActivityViewModel.cshtml")]
    public partial class _Areas_V2_Views_Shared_DisplayTemplates_ActivityViewModel_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<ActivityViewModel>
    {
        public _Areas_V2_Views_Shared_DisplayTemplates_ActivityViewModel_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
  
    var showViewMoreLink = Convert.ToBoolean(ViewData["showViewMoreLink"]);
    var showComments = Convert.ToBoolean(ViewData["showComments"]);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span12\">\r\n        <div class=\"well well-smal" +
"l activity-container\">\r\n            <img class=\"activity-image\"\r\n               " +
"  src=\"");


            
            #line 13 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                 Write(Url.ContentCacheBreak($"~/Content/css/images/{Model.AppleTouchIcon}"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                 alt=\"");


            
            #line 14 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                 Write(Model.FullTeamName);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <div class=\"activity-content-container\">\r\n                <h4 c" +
"lass=\"activity-main-title\">\r\n                    ");


            
            #line 17 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <em>\r\n                        (<time datetime=\"");


            
            #line 19 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                                     Write($"{Model.ActivityDate:s}");

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 19 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                                                                  Write(Model.ActivityDate.ToString("d MMMM HH:mm"));

            
            #line default
            #line hidden
WriteLiteral("</time>)\r\n                    </em>\r\n");


            
            #line 21 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                     if (Model.ActivityDate.ToUniversalTime() < SystemTime.UtcNow)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span class=\"label label-important\">PASSERAT</span>\r\n");


            
            #line 24 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </h4>\r\n                <h5 class=\"activity-sub-title\">\r\n         " +
"           ");


            
            #line 27 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
               Write(Model.Author);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h5>\r\n");


            
            #line 29 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                 if (showViewMoreLink)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"cropped-message-well\">");


            
            #line 31 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                                                 Write(Model.MessageHtml);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 32 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
               Write(Html.ActionLink("Visa mer", "Index", "ActivityDetails", null, null, "disqus_thread", new { Model.Id }, null));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                                                                                                                                 
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div>");


            
            #line 36 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                    Write(Model.MessageHtml);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 37 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");


            
            #line 42 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
 if (showComments)
{

            
            #line default
            #line hidden
WriteLiteral(@"    <div class=""row"">
        <div class=""span12"">
            <div id=""disqus_thread""></div>
            <script>
                /**
                 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                /*
                var disqus_config = function () {
                this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                };
                */
                (function () { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://snittlistan.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href=""https://disqus.com/?ref_noscript"">comments powered by Disqus.</a></noscript>
        </div>
    </div>
");


            
            #line 67 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ActivityViewModel.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
