#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Shared/DisplayTemplates/RosterViewModel.cshtml")]
    public partial class _Areas_V2_Views_Shared_DisplayTemplates_RosterViewModel_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<RosterViewModel>
    {
        public _Areas_V2_Views_Shared_DisplayTemplates_RosterViewModel_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
  
    var hideControls = Convert.ToBoolean(ViewData["hideControls"]);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"well well-small editable\">\r\n");


            
            #line 7 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
     if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false && Model.Header.MatchResultId == null)
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <div class=""dropdown edit-left"">
            <button class=""dropdown-toggle"" data-toggle=""dropdown"">
                <i class=""sprite-glyphicons_019_cogwheel""></i>
                <b class=""caret""></b>
            </button>
            <ul class=""dropdown-menu"">
                <li>
                    <a href=""");


            
            #line 16 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
                        Write(Url.Action("Edit", "Roster", new { id = Model.Header.RosterId }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <i class=\"sprite-glyphicons_151_edit\"></i>\r\n         " +
"               Redigera\r\n                    </a>\r\n                </li>\r\n      " +
"          <li>\r\n                    <a href=\"");


            
            #line 22 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
                        Write(Url.Action("Delete", "Roster", new { id = Model.Header.RosterId }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <i class=\"sprite-glyphicons_016_bin\"></i>\r\n          " +
"              Ta bort\r\n                    </a>\r\n                </li>\r\n        " +
"    </ul>\r\n        </div>\r\n");


            
            #line 29 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 30 "..\..\Areas\V2\Views\Shared\DisplayTemplates\RosterViewModel.cshtml"
Write(Html.DisplayFor(x => x.Header));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
