#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Shared/DisplayTemplates/ValidationSummary.cshtml")]
    public partial class _Areas_V2_Views_Shared_DisplayTemplates_ValidationSummary_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<ModelStateDictionary>
    {
        public _Areas_V2_Views_Shared_DisplayTemplates_ValidationSummary_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ValidationSummary.cshtml"
  
    var message = ViewData["message"] as string ?? "Det gick inte att spara. Försök gärna igen.";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ValidationSummary.cshtml"
 if (Html.ViewData.ModelState.IsValid == false)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"alert alert-danger\">\r\n        ");


            
            #line 10 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ValidationSummary.cshtml"
   Write(Html.ValidationSummary(false, message));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 12 "..\..\Areas\V2\Views\Shared\DisplayTemplates\ValidationSummary.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
