#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/MatchResultAdmin/EditorTemplates/Match4PostModel.cshtml")]
    public partial class _Areas_V2_Views_MatchResultAdmin_EditorTemplates_Match4PostModel_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.MatchResultAdminController.RegisterMatch4ViewModel.PostModel>
    {
        public _Areas_V2_Views_MatchResultAdmin_EditorTemplates_Match4PostModel_cshtml()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
  
    var playerListItems = (SelectListItem[])ViewData["playerListItems"];


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"span2\">\r\n        <div class=\"control-group\">" +
"\r\n            <div class=\"controls\">\r\n                ");


            
            #line 10 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
           Write(Html.LabelFor(
                    x => x.TeamScore,
                    new
                    {
                        @class = "control-label"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 16 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
           Write(Html.TextBoxFor(
                    x => x.TeamScore,
                    new
                    {
                        @class = "span1",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "20",
                        required = "required",
                        title = "0-20 poäng",
                        placeholder = "0-20"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"span2\">\r\n      " +
"  <div class=\"control-group\">\r\n            <div class=\"controls\">\r\n             " +
"   ");


            
            #line 35 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
           Write(Html.LabelFor(
                    x => x.OpponentScore,
                    new
                    {
                        @class = "control-label"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 41 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
           Write(Html.TextBoxFor(
                    x => x.OpponentScore,
                    new
                    {
                        @class = "span1",
                        type = "number",
                        pattern = @"\d*",
                        min = "0",
                        max = "20",
                        required = "required",
                        title = "0-20 poäng",
                        placeholder = "0-20"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"span8\">\r\n      " +
"  <div class=\"control-group\">\r\n            <div class=\"controls\">\r\n             " +
"   ");


            
            #line 60 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
           Write(Html.LabelFor(
                    x => x.CommentaryDisplay,
                    new
                    {
                        @class = "control-label"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div data-quill>");


            
            #line 66 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                           Write(Model.CommentaryDisplay);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            ");


            
            #line 68 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
       Write(Html.HiddenFor(x => x.Commentary));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 69 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
       Write(Html.HiddenFor(x => x.CommentaryHtml));

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
    </div>
</div>
<div class=""row"">
    <div class=""span12"">
        <p>För varje serie, ange om spelaren vann serien.</p>
        <table class=""table table-condensed table-bordered table-striped"">
            <tr>
                <th>Spelare</th>
                <th>Serie 1</th>
                <th>Serie 2</th>
                <th>Serie 3</th>
                <th>Serie 4</th>
            </tr>
");


            
            #line 84 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
             for (var i = 0; i < Model.Players.Length; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td rowspan=\"2\" style=\"vertical-align: " +
"middle;\">\r\n");


            
            #line 88 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                          
                            object opts;
                        

            
            #line default
            #line hidden

            
            #line 91 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                         if (i < 4)
                        {
                            opts = new
                            {
                                @class = "span2",
                                required = "required"
                            };
                        }
                        else
                        {
                            opts = new
                            {
                                @class = "span2",
                            };
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 107 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                   Write(Html.DropDownListFor(
                            m => m.Players[i].PlayerId,
                            playerListItems,
                            "Välj spelare",
                            opts));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");


            
            #line 113 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                     for (var j = 0; j < Model.Players[i].Games.Length; j++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td>\r\n                            ");


            
            #line 116 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                       Write(Html.TextBoxFor(
                                m => m.Players[i].Games[j].Pins,
                                new
                                {
                                    @class = "span1",
                                    type = "number",
                                    pattern = @"\d*",
                                    min = "0",
                                    max = "300"
                                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n");


            
            #line 127 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");



WriteLiteral("                <tr>\r\n");


            
            #line 130 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                     for (var j = 0; j < Model.Players[i].Games.Length; j++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td>\r\n                            <label>\r\n              " +
"                  ");


            
            #line 134 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                           Write(Html.CheckBoxFor(m => m.Players[i].Games[j].Score));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                Vann\r\n                            </label>\r\n   " +
"                     </td>\r\n");


            
            #line 138 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");


            
            #line 140 "..\..\Areas\V2\Views\MatchResultAdmin\EditorTemplates\Match4PostModel.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
