#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    
    #line 1 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
    using Snittlistan.Web.Areas.V2.Domain;
    
    #line default
    #line hidden
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Player/_PlayerEditor.cshtml")]
    public partial class _Areas_V2_Views_Player__PlayerEditor_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<Snittlistan.Web.Areas.V2.Controllers.PlayerController.CreatePlayerViewModel>
    {
        public _Areas_V2_Views_Player__PlayerEditor_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral(@"
<div class=""control-group"">
    <label class=""control-label"" for=""name"">Namn:</label>
    <div class=""controls"">
        <input type=""text""
               name=""name""
               id=""name""
               placeholder=""Fullständigt namn""
               autofocus=""autofocus""
               autocorrect=""off""
               autocomplete=""off""
               value=""");


            
            #line 15 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                 Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(@"""
               required />
        <span class=""help-block"">Måste anges</span>
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""email"">E-postadress:</label>
    <div class=""controls"">
        <input type=""email""
               name=""email""
               id=""email""
               placeholder=""""
               autocorrect=""off""
               autocomplete=""off""
               value=""");


            
            #line 29 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                 Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <span class=""help-block"">Måste anges då det möjliggör inloggning</span>
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""nickname"">Smeknamn:</label>
    <div class=""controls"">
        <input type=""text""
               name=""nickname""
               id=""nickname""
               placeholder=""Smeknamn""
               autocorrect=""off""
               autocomplete=""off""
               value=""");


            
            #line 42 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                 Write(Model.Nickname);

            
            #line default
            #line hidden
WriteLiteral(@""" />
    </div>
</div>
<div class=""control-group"">
    <label class=""control-label"" for=""personalNumber"">Födelsedag:</label>
    <div class=""controls"">
        <input type=""text""
               name=""personalNumber""
               id=""personalNumber""
               placeholder=""T.ex. 791231""
               autocorrect=""off""
               autocomplete=""off""
               pattern=""\d*""
               title=""Ange 6 siffror enligt ÅÅMMDD""
               value=""");


            
            #line 56 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                  Write(Model.PersonalNumber?.ToString() ?? string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </div>\r\n</div>\r\n<div class=\"control-group\">\r\n    <label class=\"control-" +
"label\" for=\"status\">Status:</label>\r\n    <div class=\"controls\">\r\n        <select" +
" name=\"status\" id=\"status\">\r\n            <option value=\"Active\"\r\n");


            
            #line 64 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                     if (Model.Status == Player.Status.Active) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" selected=\"selected\" ");

WriteLiteral("  ");


            
            #line 64 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                Aktiv\r\n            </option>\r\n            <option value=\"Suppo" +
"rter\"\r\n");


            
            #line 68 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                     if (Model.Status == Player.Status.Supporter) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" selected=\"selected\" ");

WriteLiteral("  ");


            
            #line 68 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                                                                                                        }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                Supporter\r\n            </option>\r\n            <option value=\"I" +
"nactive\"\r\n");


            
            #line 72 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                     if (Model.Status == Player.Status.Inactive) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" selected=\"selected\" ");

WriteLiteral("  ");


            
            #line 72 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
                                                                                                       }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                Inaktiv\r\n            </option>\r\n        </select>\r\n    </div>\r" +
"\n</div>\r\n<div class=\"control-group\">\r\n    ");


            
            #line 79 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
Write(Html.LabelFor(x => x.Roles, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"controls\">\r\n        ");


            
            #line 81 "..\..\Areas\V2\Views\Player\_PlayerEditor.cshtml"
   Write(Html.ListBoxFor(x => x.Roles, Model.RolesList, new
        {
            size = 5,
            style = "width: auto;"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span class=\"help-block\">Välj vilka funktioner medlemmen ska ha tillgån" +
"g till.</span>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
