#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snittlistan.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Snittlistan.Web.Areas.V2;
    
    #line 1 "..\..\Areas\V2\Views\Player\Index.cshtml"
    using Snittlistan.Web.Areas.V2.Domain;
    
    #line default
    #line hidden
    using Snittlistan.Web.Areas.V2.ViewModels;
    using Snittlistan.Web.HtmlHelpers;
    using Snittlistan.Web.Infrastructure;
    using Snittlistan.Web.Infrastructure.Database;
    using Snittlistan.Web.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/V2/Views/Player/Index.cshtml")]
    public partial class _Areas_V2_Views_Player_Index_cshtml : Snittlistan.Web.Infrastructure.BaseViewPage<List<PlayerViewModel>>
    {

public System.Web.WebPages.HelperResult ShowPlayer(PlayerViewModel player)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Areas\V2\Views\Player\Index.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <tr>\r\n        <td title=\"");



#line 7 "..\..\Areas\V2\Views\Player\Index.cshtml"
WriteTo(@__razor_helper_writer, player.LicenseNumber);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            ");



#line 8 "..\..\Areas\V2\Views\Player\Index.cshtml"
WriteTo(@__razor_helper_writer, player.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 9 "..\..\Areas\V2\Views\Player\Index.cshtml"
             if (string.IsNullOrEmpty(player.Nickname) == false)
            {
                
#line default
#line hidden


#line 11 "..\..\Areas\V2\Views\Player\Index.cshtml"
WriteTo(@__razor_helper_writer, $"({player.Nickname})");

#line default
#line hidden


#line 11 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                         
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </td>\r\n        <td>");



#line 14 "..\..\Areas\V2\Views\Player\Index.cshtml"
WriteTo(@__razor_helper_writer, player.StatusText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n");



#line 15 "..\..\Areas\V2\Views\Player\Index.cshtml"
         if (User.IsInRole2(WebsiteRoles.Player.ShowEmailAddresses))
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <td>\r\n");



#line 18 "..\..\Areas\V2\Views\Player\Index.cshtml"
                 if (player.Email != null)
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <a href=\"mailto:");



#line 20 "..\..\Areas\V2\Views\Player\Index.cshtml"
     WriteTo(@__razor_helper_writer, player.Email);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 20 "..\..\Areas\V2\Views\Player\Index.cshtml"
                    WriteTo(@__razor_helper_writer, player.Email);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 21 "..\..\Areas\V2\Views\Player\Index.cshtml"
                }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            </td>\r\n");



#line 23 "..\..\Areas\V2\Views\Player\Index.cshtml"
        }

#line default
#line hidden



#line 24 "..\..\Areas\V2\Views\Player\Index.cshtml"
         if (User.IsInRole2(WebsiteRoles.Player.Admin))
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <td>\r\n                <a href=\"");



#line 27 "..\..\Areas\V2\Views\Player\Index.cshtml"
WriteTo(@__razor_helper_writer, Url.Action("Edit", new { id = player.Id.Substring(player.Id.LastIndexOf('-') + 1) }));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                    <i class=\"sprite-glyphicons_151_edit\"></i>\r\n             " +
"   </a>\r\n            </td>\r\n");



#line 31 "..\..\Areas\V2\Views\Player\Index.cshtml"
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    </tr>\r\n");



#line 33 "..\..\Areas\V2\Views\Player\Index.cshtml"
     if (User.IsInRole2(WebsiteRoles.Player.Admin) && player.Roles.Any())
     {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "         <tr>\r\n             <td colspan=\"4\">\r\n");



#line 37 "..\..\Areas\V2\Views\Player\Index.cshtml"
                  foreach (var role in player.Roles)
                 {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                     <span class=\"badge badge-info\">");



#line 39 "..\..\Areas\V2\Views\Player\Index.cshtml"
                     WriteTo(@__razor_helper_writer, role);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 40 "..\..\Areas\V2\Views\Player\Index.cshtml"
                 }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "             </td>\r\n         </tr>\r\n");



#line 43 "..\..\Areas\V2\Views\Player\Index.cshtml"
     }

#line default
#line hidden

});

}


        public _Areas_V2_Views_Player_Index_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n<div class=\"row\">\r\n    <div class=\"span6\">\r\n        <h4>Spelare och supporter" +
"s</h4>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"span8\">\r\n");


            
            #line 53 "..\..\Areas\V2\Views\Player\Index.cshtml"
         if (User.IsInRole2(WebsiteRoles.Player.Admin))
        {

            
            #line default
            #line hidden
WriteLiteral("            <a class=\"pull-left\" href=\"");


            
            #line 55 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                  Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <i class=\"sprite-glyphicons_006_user_add\"></i>\r\n             " +
"   Lägg till spelare\r\n            </a>\r\n");


            
            #line 59 "..\..\Areas\V2\Views\Player\Index.cshtml"
        }

            
            #line default
            #line hidden

            
            #line 60 "..\..\Areas\V2\Views\Player\Index.cshtml"
         if (User.IsInRole2(WebsiteRoles.Player.ShowEmailAddresses))
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""btn-group pull-right"">
                <button type=""button"" class=""btn btn-small btn-primary dropdown-toggle"" data-toggle=""dropdown"">
                    Skicka e-post
                    <span class=""caret""></span>
                </button>
                <ul class=""dropdown-menu"">
                    <li>
                        <a href=""mailto:");


            
            #line 69 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                   Write(string.Join(",", new HashSet<string>(Model.Where(x => x.Status != Player.Status.Inactive && x.Email != null).Select(x => x.Email))));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Till alla (komma-separerade; iPhone/Android)\r\n   " +
"                     </a>\r\n                    </li>\r\n                    <li>\r\n" +
"                        <a href=\"mailto:");


            
            #line 74 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                   Write(string.Join(";", new HashSet<string>(Model.Where(x => x.Status != Player.Status.Inactive && x.Email != null).Select(x => x.Email))));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Till alla (semikolon-separerade; Outlook)\r\n      " +
"                  </a>\r\n                    </li>\r\n                </ul>\r\n      " +
"      </div>\r\n");



WriteLiteral("            <div class=\"clearfix\"></div>\r\n");


            
            #line 81 "..\..\Areas\V2\Views\Player\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"span8\">\r\n        <table cl" +
"ass=\"table table-condensed table-striped\">\r\n            <tr>\r\n                <t" +
"h>Namn</th>\r\n                <th>Status</th>\r\n");


            
            #line 90 "..\..\Areas\V2\Views\Player\Index.cshtml"
                 if (User.IsInRole2(WebsiteRoles.Player.ShowEmailAddresses))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th>E-postadress</th>\r\n");



WriteLiteral("                    <th></th>\r\n");


            
            #line 94 "..\..\Areas\V2\Views\Player\Index.cshtml"
                    
            
            #line default
            #line hidden

            
            #line 94 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                 
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");


            
            #line 97 "..\..\Areas\V2\Views\Player\Index.cshtml"
             foreach (var player in Model.Where(x => x.Status == Player.Status.Active))
            {
                
            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\V2\Views\Player\Index.cshtml"
           Write(ShowPlayer(player));

            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                   
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 102 "..\..\Areas\V2\Views\Player\Index.cshtml"
             foreach (var player in Model.Where(x => x.Status == Player.Status.Supporter))
            {
                
            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\V2\Views\Player\Index.cshtml"
           Write(ShowPlayer(player));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                   
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 107 "..\..\Areas\V2\Views\Player\Index.cshtml"
             if (User.IsInRole2(WebsiteRoles.Player.Admin))
            {
                foreach (var player in Model.Where(x => x.Status == Player.Status.Inactive))
                {
                    
            
            #line default
            #line hidden
            
            #line 111 "..\..\Areas\V2\Views\Player\Index.cshtml"
               Write(ShowPlayer(player));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Areas\V2\Views\Player\Index.cshtml"
                                       
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
