name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore
      run: msbuild -t:restore Snittlistan.sln

    - name: Build
      run: msbuild -t:Build -p:Configuration=Release Snittlistan.sln
